## Section 1: Combining Data

Additional examples of [data wrangling in Pandas](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

### `pd.concat()`
- **Purpose**: Combines multiple DataFrames into one.

- **Key Parameter**:
    - `ignore_index`: When set to `True` resets the index so that the resulting DataFrame has a new continuous index.

In [2]:
import pandas as pd

# Department 1 data
df_dept1 = pd.DataFrame({
    'EmployeeID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Michael'],
    'Department': ['Sales', 'Sales', 'Sales'],
    'Salary': [60000, 62000, 61000]
})

# Department 2 data
df_dept2 = pd.DataFrame({
    'EmployeeID': [104, 105],
    'Name': ['David', 'Henry'],
    'Department': ['Marketing', 'Marketing'],
    'Salary': [65000, 67000]
})

df_employees = pd.concat([df_dept1, df_dept2], ignore_index = True)

### `rename()`
- **Purpose**: Changes column names to more meaningful or standardized labels.
- **Key Parameter**:
    - `columns`: A dictionary mapping old column names to new names.

In [3]:
# Rename columns to more descriptive names
df_employees_renamed = df_employees.rename(columns = {
    #Key: value pairs
    #old name: new name
    "EmployeeID": "Emp_ID",
    "Name": "Emp_Name",
    "Department": "Dept",
    "Salary": "Annual_Salary"
})

df_employees_renamed

   Emp_ID Emp_Name       Dept  Annual_Salary
0     101    Alice      Sales          60000
1     102      Bob      Sales          62000
2     103  Michael      Sales          61000
3     104    David  Marketing          65000
4     105    Henry  Marketing          67000

### `sort_values()`
- **Purpose**: Sorts the DataFrame by a specific column.
- **Key Parameter**:
    - `by`: Specifies the column(s) to sort by.
    - `ascending`: When set to `False` sorts the data in descending order.

In [12]:
# Sort by Annual_Salary in descending order
df_employees_renamed.sort_values(by = "Annual_Salary",
                                 ascending = False,
                                   inplace = True) 
df_employees_renamed

   Emp_ID Emp_Name       Dept  Annual_Salary
4     105    Henry  Marketing          67000
3     104    David  Marketing          65000
1     102      Bob      Sales          62000
2     103  Michael      Sales          61000
0     101    Alice      Sales          60000

## Section 2: Method Chaining

### **Concept**: Combining several DataFrame operations into one continuous expression.

### **Advantages**:
- Improves readability and conciseness.
- Reduces the need for intermediate variables.

### Steps in this chain:
- **Concatenation**: Merges the two department DataFrames.
- **Renaming**: Standardizes column names.
- **Sorting**: Orders the DataFrame by annual salary in descending order.

In [ ]:
import pandas as pd

# Department 1 data
df_dept1 = pd.DataFrame({
    'EmployeeID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Michael'],
    'Department': ['Sales', 'Sales', 'Sales'],
    'Salary': [60000, 62000, 61000]
})

# Department 2 data
df_dept2 = pd.DataFrame({
    'EmployeeID': [104, 105],
    'Name': ['David', 'Henry'],
    'Department': ['Marketing', 'Marketing'],
    'Salary': [65000, 67000]
})

# Method chaining: Combine, rename, and sort in descending order of salary.
df_employees = (pd.concat([df_dept1, df_dept2, ignore_index = True)
.rename[columns = {
    "EmployeeID": "Emp_ID"
    "Name": {"David", "Henry"},
    "Department": "Dept",
    "Salary": "Annual_Salary"
}])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (2435272406.py, line 20)

## Group Activity: Cleaning an Untidy Sales Dataset Using Method Chaining

### Method Chaining Instructions:
- Remove duplicates.
- Fill missing values with 0.
- Reshape the DataFrame from wide to long format.
- Sort the final DataFrame.

In [ ]:
import pandas as pd

df_sales = pd.DataFrame({
    'Product': [
        'Widget A', 'Widget B', 'Widget A', 'Widget C',
        'Widget B', 'Widget A', 'Widget D', 'Widget E',
        'Widget C', 'Widget D', 'Widget B', 'Widget E'
    ],
    'Region': [
        'North', 'South', 'North', 'East',
        'South', 'North', 'West', 'East',
        'Central', 'North', 'West', 'South'
    ],
    'Sales_Q1': [100, 200, 100, 150, None, 100, 180, 210, 140, 190, 205, 220],
    'Sales_Q2': [110, None, 110, 160, 210, 110, 185, 220, 150, 200, 215, 230],
    'Sales_Q3': [105, 205, 105, None, 215, 105, 175, 205, 145, 195, 210, 225],
    'Sales_Q4': [115, 215, 115, 165, 225, None, 190, 215, 155, 205, 220, 235]
})

print("Expanded df_sales DataFrame:")
#print(df_sales)


# Method chaining: Clean the dataset in one pipeline.
df_sales_clean = (df_sales
.drop.duplicates(
.fillna(0)
.melt(id_vars=["Product", "Region"],
      value_vars = ["Sales_Q1", "Sales_Q2", "Sales_Q3", "Sales_Q4"],
      var_name = "Quarter",
      value_name = ""
            ])
)
df_sales_clean

Expanded df_sales DataFrame:

NameError: name 'df' is not defined

In [ ]:
# Create a pivot table that calculates the sum of sales per Product per Region